import * as React from 'react';
import { toast } from 'sonner';
import { Bookmark, BookmarkCheck, ExternalLink, Sparkles, Search } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { PageHeader, Spinner } from '@/components/ui/misc';
import { Button } from '@/components/ui/button';
import { Modal } from '@/components/ui/modal';
import { Input, Select } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { listGrants, getTenantProfile, listReferralPartners } from '@/lib/store';
import { callAI } from '@/lib/ai';
import type { Grant } from '@culina/shared';
import { format } from 'date-fns';

export default function Grants() {
  const { profile } = useAuth();
  const tp = getTenantProfile(profile!.id);
  const grants = listGrants();
  const [q, setQ] = React.useState('');
  const [type, setType] = React.useState('all');
  const [saved, setSaved] = React.useState<Set<string>>(new Set());
  const [drafting, setDrafting] = React.useState<Grant | null>(null);
  const [draft, setDraft] = React.useState('');
  const [loading, setLoading] = React.useState(false);

  const filtered = grants.filter((g) => {
    if (type !== 'all' && g.grant_type !== type) return false;
    if (!q.trim()) return true;
    return `${g.title} ${g.funder} ${g.description}`.toLowerCase().includes(q.toLowerCase());
  });

  function toggleSave(id: string) {
    setSaved((s) => {
      const next = new Set(s);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  async function openDraft(g: Grant) {
    setDrafting(g);
    setDraft('');
    setLoading(true);
    const fallback = [
      `EXECUTIVE SUMMARY`,
      `${tp?.business_name ?? 'Our business'} respectfully requests support from the ${g.funder} ${g.title}. We are a ${tp?.business_type ?? 'small food'} business operating from a shared commercial kitchen, with ${tp?.years_in_operation ?? 'several'} years of operation and an estimated ${tp?.annual_revenue_estimate ? '$' + tp.annual_revenue_estimate.toLocaleString() : 'modest'} in annual revenue.`,
      ``,
      `NEED & OPPORTUNITY`,
      `Like many early-stage food makers, our growth is constrained by access to capital for equipment, packaging, and inventory. This funding would directly expand our production capacity and create local economic value.`,
      ``,
      `USE OF FUNDS`,
      `Requested funds would be allocated toward equipment time, ingredient inventory at scale, and compliant packaging — each a documented bottleneck to our next stage of growth.`,
      ``,
      `IMPACT`,
      `Our business reflects the communities this program serves. Investment here compounds: as we grow, we hire locally, source locally, and mentor the makers who follow.`,
      ``,
      `(Draft generated by Culina AI — review, personalize, and verify all figures before submitting.)`,
    ].join('\n');
    const text = await callAI('draft-grant', { grant: g.description, business: tp }, fallback);
    setDraft(text);
    setLoading(false);
  }

  const partners = listReferralPartners();

  return (
    <div>
      <PageHeader title="Grant Finder" description="Funding for food entrepreneurs — federal, state, foundation, and loans." />

      <div className="mb-6 rounded-xl border border-accent/30 bg-accent/5 p-5">
        <h2 className="font-heading font-semibold">Get matched with a funding partner</h2>
        <p className="mt-1 text-sm text-muted-foreground">Culina works with lenders, CDFIs, and insurers who fund makers like you. Introductions are free.</p>
        <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {partners.map((p) => (
            <div key={p.id} className="flex flex-col rounded-lg border bg-card p-4">
              <div className="text-sm font-medium">{p.name}</div>
              <div className="mt-1 flex-1 text-xs text-muted-foreground">{p.description}</div>
              <Button size="sm" variant="outline" className="mt-3" onClick={() => toast.success(`Intro requested to ${p.name} (demo)`)}>Request intro</Button>
            </div>
          ))}
        </div>
      </div>

      <div className="mb-4 flex flex-col gap-2 sm:flex-row">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input className="pl-9" placeholder="Search grants…" value={q} onChange={(e) => setQ(e.target.value)} />
        </div>
        <Select value={type} onChange={(e) => setType(e.target.value)} className="sm:w-48">
          <option value="all">All types</option>
          <option value="federal">Federal</option>
          <option value="state">State</option>
          <option value="local">Local</option>
          <option value="foundation">Foundation</option>
          <option value="loan">Loan</option>
        </Select>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {filtered.map((g) => (
          <div key={g.id} className="flex flex-col rounded-lg border bg-card p-5 shadow-card">
            <div className="flex items-start justify-between">
              <div>
                <h3 className="font-heading font-semibold">{g.title}</h3>
                <div className="text-xs text-muted-foreground">{g.funder}</div>
              </div>
              <button onClick={() => toggleSave(g.id)} className="text-primary">{saved.has(g.id) ? <BookmarkCheck className="h-5 w-5" /> : <Bookmark className="h-5 w-5" />}</button>
            </div>
            <p className="mt-2 flex-1 text-sm text-muted-foreground">{g.description}</p>
            <div className="mt-3 flex flex-wrap items-center gap-2">
              <Badge>{g.grant_type}</Badge>
              {g.amount_min != null && <Badge variant="muted">${g.amount_min.toLocaleString()}–${g.amount_max?.toLocaleString()}</Badge>}
              {g.deadline && <Badge variant="warning">Due {format(new Date(g.deadline), 'MMM d')}</Badge>}
            </div>
            <div className="mt-4 flex gap-2">
              <Button size="sm" variant="accent" onClick={() => openDraft(g)}><Sparkles className="h-3 w-3" /> AI draft</Button>
              {g.application_url && <a href={g.application_url} target="_blank" rel="noreferrer"><Button size="sm" variant="outline"><ExternalLink className="h-3 w-3" /> Apply</Button></a>}
            </div>
          </div>
        ))}
      </div>

      <Modal open={!!drafting} onClose={() => setDrafting(null)} title={`Application draft: ${drafting?.title ?? ''}`} className="max-w-2xl">
        {loading ? (
          <div className="flex items-center justify-center gap-2 py-10 text-sm text-muted-foreground"><Spinner /> Drafting your application…</div>
        ) : (
          <>
            <pre className="max-h-[55vh] overflow-y-auto whitespace-pre-wrap rounded-lg border bg-muted/40 p-4 text-sm leading-relaxed">{draft}</pre>
            <Button className="mt-3 w-full" onClick={() => { navigator.clipboard?.writeText(draft); toast.success('Copied to clipboard'); }}>Copy draft</Button>
          </>
        )}
      </Modal>
    </div>
  );
}
